import type { CourseListing } from "@/types/course-listing";

const thumb = (slug: string, alt: string) => ({
  thumbnailUrl: `/course-thumbnails/${slug}.jpg`,
  thumbnailAlt: alt,
});

/** Demo courses — replace with Supabase fetch when backend is ready */
export const MOCK_COURSES: CourseListing[] = [
  {
    id: "1",
    slug: "intro-machine-learning",
    title: "Introduction to Machine Learning",
    summary:
      "Core ML concepts from a popular TED-style talk — supervised learning, neural networks, and real-world applications.",
    sourceType: "youtube",
    language: "en",
    difficulty: "beginner",
    conceptCount: 7,
    flashcardCount: 10,
    quizCount: 5,
    createdAt: "2026-05-15T10:00:00Z",
    author: "SkillProof",
    ...thumb(
      "intro-machine-learning",
      "Neural network visualization representing machine learning",
    ),
  },
  {
    id: "2",
    slug: "climate-change-basics",
    title: "Climate Change: The Science Explained",
    summary:
      "Understand greenhouse gases, climate models, and actionable steps from a leading environmental article.",
    sourceType: "article",
    language: "en",
    difficulty: "beginner",
    conceptCount: 6,
    flashcardCount: 10,
    quizCount: 5,
    createdAt: "2026-05-14T14:30:00Z",
    author: "SkillProof",
    ...thumb(
      "climate-change-basics",
      "Earth from space illustrating climate and environment",
    ),
  },
  {
    id: "3",
    slug: "financial-literacy-101",
    title: "Personal Finance Fundamentals",
    summary:
      "Budgeting, compound interest, and investing basics distilled from a comprehensive PDF guide.",
    sourceType: "pdf",
    language: "en",
    difficulty: "beginner",
    conceptCount: 8,
    flashcardCount: 10,
    quizCount: 5,
    createdAt: "2026-05-13T09:15:00Z",
    author: "SkillProof",
    ...thumb(
      "financial-literacy-101",
      "Coins and savings representing personal finance",
    ),
  },
  {
    id: "4",
    slug: "spanish-conversation",
    title: "Spanish Conversation Essentials",
    summary:
      "Everyday phrases, pronunciation tips, and cultural context for beginner Spanish learners.",
    sourceType: "youtube",
    language: "es",
    difficulty: "beginner",
    conceptCount: 7,
    flashcardCount: 10,
    quizCount: 5,
    createdAt: "2026-05-12T16:45:00Z",
    author: "SkillProof",
    ...thumb(
      "spanish-conversation",
      "Colorful European city street for Spanish language learning",
    ),
  },
  {
    id: "5",
    slug: "product-management-agile",
    title: "Agile Product Management",
    summary:
      "Sprints, backlogs, and stakeholder management — a practical course for aspiring PMs.",
    sourceType: "article",
    language: "en",
    difficulty: "intermediate",
    conceptCount: 8,
    flashcardCount: 10,
    quizCount: 5,
    createdAt: "2026-05-11T11:20:00Z",
    author: "SkillProof",
    ...thumb(
      "product-management-agile",
      "Team collaborating in an agile product meeting",
    ),
  },
  {
    id: "6",
    slug: "blockchain-explained",
    title: "Blockchain & Cryptocurrency Explained",
    summary:
      "How distributed ledgers work, what Bitcoin actually is, and the promise of Web3.",
    sourceType: "youtube",
    language: "en",
    difficulty: "intermediate",
    conceptCount: 7,
    flashcardCount: 10,
    quizCount: 5,
    createdAt: "2026-05-10T08:00:00Z",
    author: "SkillProof",
    ...thumb(
      "blockchain-explained",
      "Bitcoin and cryptocurrency concept",
    ),
  },
  {
    id: "7",
    slug: "public-speaking-mastery",
    title: "Public Speaking Mastery",
    summary:
      "Overcome stage fright, structure compelling talks, and deliver with confidence.",
    sourceType: "audio",
    language: "en",
    difficulty: "intermediate",
    conceptCount: 6,
    flashcardCount: 10,
    quizCount: 5,
    createdAt: "2026-05-09T13:30:00Z",
    author: "SkillProof",
    ...thumb(
      "public-speaking-mastery",
      "Conference speaker presenting on stage",
    ),
  },
  {
    id: "8",
    slug: "data-structures-algorithms",
    title: "Data Structures & Algorithms",
    summary:
      "Arrays, trees, graphs, and Big-O notation — essential CS fundamentals for interviews.",
    sourceType: "pdf",
    language: "en",
    difficulty: "expert",
    conceptCount: 8,
    flashcardCount: 10,
    quizCount: 5,
    createdAt: "2026-05-08T17:00:00Z",
    author: "SkillProof",
    ...thumb(
      "data-structures-algorithms",
      "Developer coding on laptop for programming",
    ),
  },
  {
    id: "9",
    slug: "mindfulness-meditation",
    title: "Mindfulness & Meditation Basics",
    summary:
      "Breathing techniques, body scans, and building a daily practice for mental clarity.",
    sourceType: "youtube",
    language: "en",
    difficulty: "beginner",
    conceptCount: 5,
    flashcardCount: 10,
    quizCount: 5,
    createdAt: "2026-05-07T10:45:00Z",
    author: "SkillProof",
    ...thumb(
      "mindfulness-meditation",
      "Person meditating in a calm natural setting",
    ),
  },
  {
    id: "10",
    slug: "digital-marketing-fundamentals",
    title: "Digital Marketing Fundamentals",
    summary:
      "SEO, social media strategy, and conversion optimization for modern brands.",
    sourceType: "article",
    language: "en",
    difficulty: "intermediate",
    conceptCount: 7,
    flashcardCount: 10,
    quizCount: 5,
    createdAt: "2026-05-06T15:20:00Z",
    author: "SkillProof",
    ...thumb(
      "digital-marketing-fundamentals",
      "Analytics dashboard for digital marketing",
    ),
  },
  {
    id: "11",
    slug: "japanese-hiragana",
    title: "Japanese Hiragana & Katakana",
    summary:
      "Master the two basic Japanese syllabaries with mnemonics and practice drills.",
    sourceType: "pdf",
    language: "ja",
    difficulty: "beginner",
    conceptCount: 6,
    flashcardCount: 10,
    quizCount: 5,
    createdAt: "2026-05-05T12:00:00Z",
    author: "SkillProof",
    ...thumb(
      "japanese-hiragana",
      "Japanese cultural scene for language learning",
    ),
  },
  {
    id: "12",
    slug: "leadership-teams",
    title: "Leadership for High-Performing Teams",
    summary:
      "Psychological safety, feedback frameworks, and motivating distributed teams.",
    sourceType: "audio",
    language: "en",
    difficulty: "expert",
    conceptCount: 8,
    flashcardCount: 10,
    quizCount: 5,
    createdAt: "2026-05-04T09:30:00Z",
    author: "SkillProof",
    ...thumb(
      "leadership-teams",
      "Diverse team collaborating on a project",
    ),
  },
];
